info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples

---
spring:
  profiles: dev
  cloud:
    config:
      uri: http://localhost:8888

---
spring:
  profiles: prod
  cloud:
    config:
      uri: http://prod.server.com:8888
